# Generated by Django 4.0.3 on 2022-04-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHotel', models.CharField(blank=True, max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('stars', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(blank=True)),
                ('image', models.TextField(blank=True, unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(blank=True)),
                ('dateStart', models.DateTimeField(auto_now_add=True)),
                ('dateEnd', models.TextField(blank=True)),
                ('isReserved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.rooms')),
            ],
        ),
    ]
