# Generated by Django 4.0.3 on 2022-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_rooms_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='isReserved',
        ),
        migrations.AddField(
            model_name='rooms',
            name='isReserved',
            field=models.BooleanField(default=False),
        ),
    ]
